source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'lightsaber_Example', :exclusive => true do
  pod "lightsaber", :path => "../"
end

target 'lightsaber_Tests', :exclusive => true do
  pod "lightsaber", :path => "../"

  pod 'Nimble'
  pod 'OAuthSwift', '~> 0.4.6'
  pod 'Alamofire', '~> 3.0.0-beta.3'
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
end
